spring.datasource.url=jdbc:derby://localhost:1527/myDatabase;create=true
spring.datasource.username=yourUser
spring.datasource.password=yourPassword
spring.datasource.driver-class-name=org.apache.derby.jdbc.ClientDriver
server.port=8081
logging.file.name=./logs/app-infra-server.log
rocketmq.name-server=localhost:9876
rocketmq.producer.group=event-consumer-group

management.endpoints.web.exposure.include=health,metrics,prometheus,info
management.endpoints.web.exposure.include=* 
management.endpoint.prometheus.enabled=true 