INSERT INTO API_EVENT_DETAILS (EVENT_ID, EVENT_STATUS, EVENT_SCORE) VALUES (1, TRUE,  '100:200');
INSERT INTO API_EVENT_DETAILS (EVENT_ID, EVENT_STATUS, EVENT_SCORE) VALUES (2, FALSE, '300:400');
INSERT INTO API_EVENT_DETAILS (EVENT_ID, EVENT_STATUS, EVENT_SCORE) VALUES (3, TRUE,  '500:600');
INSERT INTO API_EVENT_DETAILS (EVENT_ID, EVENT_STATUS, EVENT_SCORE) VALUES (4, TRUE,  '700:800');
INSERT INTO API_EVENT_DETAILS (EVENT_ID, EVENT_STATUS, EVENT_SCORE) VALUES (5, FALSE, '900:100');
