DROP TABLE IF EXISTS API_EVENT_DETAILS;
CREATE TABLE API_EVENT_DETAILS (
    EVENT_ID    BIGINT       NOT NULL,
    EVENT_STATUS BOOLEAN     DEFAULT FALSE,
    EVENT_SCORE  VARCHAR(255),
    CONSTRAINT PK_API_EVENT PRIMARY KEY (EVENT_ID)
);
