server.port=9090

spring.datasource.url=jdbc:derby://localhost:1527/myDatabase
spring.datasource.username=yourUser
spring.datasource.password=yourPassword
spring.datasource.driver-class-name=org.apache.derby.jdbc.ClientDriver

logging.file.name=./logs/app-mock-server.log

management.endpoints.web.exposure.include=health,metrics,prometheus,info
management.endpoints.web.exposure.include=* 
management.endpoint.prometheus.enabled=true 

rocketmq.name-server=localhost:9876
rocketmq.producer.group=mock-consumer-group

app.event.get.sql=SELECT EVENT_ID,EVENT_STATUS,EVENT_SCORE FROM MOCK_EVENT_DETAILS WHERE EVENT_ID = ?
app.event.getalllive.sql=SELECT EVENT_ID,EVENT_STATUS,EVENT_SCORE FROM MOCK_EVENT_DETAILS WHERE EVENT_STATUS = TRUE
app.event.add.sql=INSERT INTO MOCK_EVENT_DETAILS (EVENT_STATUS,EVENT_SCORE) VALUES (?,?)
app.event.update.sql=UPDATE MOCK_EVENT_DETAILS SET EVENT_STATUS = ?, EVENT_SCORE=? WHERE EVENT_ID = ?
app.event.remove.sql=DELETE FROM MOCK_EVENT_DETAILS WHERE EVENT_ID = ?