INSERT INTO MOCK_EVENT_DETAILS (EVENT_STATUS, EVENT_SCORE) VALUES (TRUE,  '100:200');
INSERT INTO MOCK_EVENT_DETAILS (EVENT_STATUS, EVENT_SCORE) VALUES (FALSE, '300:400');
INSERT INTO MOCK_EVENT_DETAILS (EVENT_STATUS, EVENT_SCORE) VALUES (TRUE,  '500:600');
INSERT INTO MOCK_EVENT_DETAILS (EVENT_STATUS, EVENT_SCORE) VALUES (TRUE,  '700:800');
INSERT INTO MOCK_EVENT_DETAILS (EVENT_STATUS, EVENT_SCORE) VALUES (FALSE, '900:100');
