DROP TABLE IF EXISTS MOCK_EVENT_DETAILS;
CREATE TABLE MOCK_EVENT_DETAILS (
    EVENT_ID     BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT_STATUS BOOLEAN      DEFAULT FALSE,
    EVENT_SCORE  VARCHAR(255)
);
